---
# tasks file for asquarezone.apache
- name: install apache on debian
  apt:
    name: "{{apache_package_deb}}"
    state: present
  when: ansible_os_family == "Debian"
- name: install apache on rhel
  yum: 
    name: "{{apche_package_rhel}}"
    state: present
  when: ansible_os_family == "Redaht"
- name: set service name for Debian
  set_fact:
    apache_package: "{{apache_package_deb}}"
  when: ansible_os_family == "Debian"
- name: set service name for Redaht
  set_fact:
    apache_package: "{{apche_package_rhel}}"
  when: ansible_os_family == "Redaht"
- name: service enabled start
  service:
    name: "{{apache_package}}"
    enabled: yes
    state: started 
- name: test by print
  debug:
    msg: firing notification for redaht
  notify: restart rhel apache
  when: ansible_os_family == "Redaht"  

  